In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/machine-predictive-maintenance-classification/predictive_maintenance.csv

In [2]:
df = pd.read_csv("/kaggle/input/machine-predictive-maintenance-classification/predictive_maintenance.csv")

In [3]:
df

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure
...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,No Failure
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,No Failure
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,No Failure
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,No Failure
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,No Failure

In [4]:
df['Target'].value_counts()

Target
0    9661
1     339
Name: count, dtype: int64

In [5]:
df.columns = ['UDI', 'Product ID', 'Type', 'Air temperature', 'Process temperature', 'Rotational speed', 'Torque', 'Tool wear', 'Target', 'Failure Type']
df

,UDI,Product ID,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure
...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,No Failure
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,No Failure
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,No Failure
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,No Failure
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,No Failure

In [6]:
from sklearn.model_selection import train_test_split

train,test = train_test_split(df, test_size=0.20, random_state=1)

In [7]:
df.shape

(10000, 10)

In [8]:
train.shape

(8000, 10)

In [9]:
test.shape

(2000, 10)

In [10]:
train['Type'].unique()

array(['M', 'L', 'H'], dtype=object)

In [11]:
train['Type'].value_counts()

Type
L    4804
M    2417
H     779
Name: count, dtype: int64

In [12]:
train.groupby(['Type'])['Target'].mean()

Type
H    0.019255
L    0.039550
M    0.029375
Name: Target, dtype: float64

In [13]:
train['Type'] = train['Type'].replace(['M','L','H'], [1,2,3])

In [14]:
test['Type'] = test['Type'].replace(['M','L','H'], [1,2,3])

In [15]:
test

,UDI,Product ID,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Target,Failure Type
9953,9954,L57133,2,298.1,307.8,1565,35.3,119,0,No Failure
3850,3851,M18710,1,302.3,311.0,1421,41.3,182,0,No Failure
4962,4963,M19822,1,304.0,312.7,1456,51.2,160,0,No Failure
3886,3887,L51066,2,302.4,311.3,1392,50.5,51,0,No Failure
5437,5438,M20297,1,302.9,312.6,1394,46.4,82,0,No Failure
...,...,...,...,...,...,...,...,...,...,...
3919,3920,H33333,3,302.5,311.5,1655,32.3,142,0,No Failure
162,163,L47342,2,298.3,308.1,1586,35.5,0,0,No Failure
7903,7904,L55083,2,300.8,312.3,1435,44.8,134,0,No Failure
2242,2243,L49422,2,299.2,308.4,1667,29.0,199,0,No Failure
2745,2746,M17605,1,299.7,309.1,1603,38.5,170,0,No Failure

In [16]:
train = train.drop(['Product ID','UDI'], axis=1)

In [17]:
test = test.drop(['Product ID','UDI'], axis=1)
test

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Target,Failure Type
9953,2,298.1,307.8,1565,35.3,119,0,No Failure
3850,1,302.3,311.0,1421,41.3,182,0,No Failure
4962,1,304.0,312.7,1456,51.2,160,0,No Failure
3886,2,302.4,311.3,1392,50.5,51,0,No Failure
5437,1,302.9,312.6,1394,46.4,82,0,No Failure
...,...,...,...,...,...,...,...,...
3919,3,302.5,311.5,1655,32.3,142,0,No Failure
162,2,298.3,308.1,1586,35.5,0,0,No Failure
7903,2,300.8,312.3,1435,44.8,134,0,No Failure
2242,2,299.2,308.4,1667,29.0,199,0,No Failure
2745,1,299.7,309.1,1603,38.5,170,0,No Failure

In [18]:
train = train.drop(['Failure Type'], axis=1)
train

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Target
2694,1,300.1,309.6,1625,38.0,46,0
5140,1,304.3,313.6,1585,32.1,202,0
2568,2,299.6,309.2,1450,43.1,160,0
3671,1,302.3,311.7,1486,39.6,147,0
7427,2,300.0,311.4,1634,31.9,0,0
...,...,...,...,...,...,...,...
2895,1,300.7,309.6,1473,48.1,87,0
7813,2,300.0,311.5,1455,41.7,130,0
905,2,295.6,306.1,1474,41.2,156,0
5192,2,303.9,313.1,1310,62.9,130,0
235,1,298.1,308.3,1680,33.7,185,0

In [19]:
test = test.drop(['Failure Type'], axis=1)
test

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Target
9953,2,298.1,307.8,1565,35.3,119,0
3850,1,302.3,311.0,1421,41.3,182,0
4962,1,304.0,312.7,1456,51.2,160,0
3886,2,302.4,311.3,1392,50.5,51,0
5437,1,302.9,312.6,1394,46.4,82,0
...,...,...,...,...,...,...,...
3919,3,302.5,311.5,1655,32.3,142,0
162,2,298.3,308.1,1586,35.5,0,0
7903,2,300.8,312.3,1435,44.8,134,0
2242,2,299.2,308.4,1667,29.0,199,0
2745,1,299.7,309.1,1603,38.5,170,0

In [20]:
y = train['Target']
y

2694    0
5140    0
2568    0
3671    0
7427    0
       ..
2895    0
7813    0
905     0
5192    0
235     0
Name: Target, Length: 8000, dtype: int64

In [21]:
X = train.drop(['Target'],axis=1)
X

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
2694,1,300.1,309.6,1625,38.0,46
5140,1,304.3,313.6,1585,32.1,202
2568,2,299.6,309.2,1450,43.1,160
3671,1,302.3,311.7,1486,39.6,147
7427,2,300.0,311.4,1634,31.9,0
...,...,...,...,...,...,...
2895,1,300.7,309.6,1473,48.1,87
7813,2,300.0,311.5,1455,41.7,130
905,2,295.6,306.1,1474,41.2,156
5192,2,303.9,313.1,1310,62.9,130
235,1,298.1,308.3,1680,33.7,185

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.30, random_state=1)

In [23]:
X_train.shape, y_train.shape, X_valid.shape, y_valid.shape

((5600, 6), (5600,), (2400, 6), (2400,))

In [24]:
from lightgbm import LGBMClassifier
model = LGBMClassifier()

In [25]:
model.fit(X_train, y_train)

LGBMClassifier()

In [26]:
X_train

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
5608,1,303.1,312.3,1623,31.6,101
7612,1,300.5,311.4,1743,27.6,46
8572,1,297.7,308.5,1559,35.2,127
5723,1,302.3,311.8,1475,48.0,180
7596,2,300.5,311.1,1547,37.2,7
...,...,...,...,...,...,...
7586,2,300.4,311.1,1589,35.5,191
8288,1,298.8,310.6,1640,33.8,9
9718,2,298.9,309.9,1517,36.6,117
7562,1,300.3,311.1,1350,58.7,130
7029,2,300.6,310.6,1454,39.7,67

In [27]:
pred_train = model.predict(X_train)

In [28]:
(pred_train == y_train).mean()

1.0

In [29]:
pred_valid = model.predict(X_valid)
pred_valid

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
(pred_valid == y_valid).mean()

0.98375

In [31]:
y_test = test['Target']
X_test = test.drop(['Target'],axis=1)
y_test

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Target, Length: 2000, dtype: int64

In [32]:
X_test

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
9953,2,298.1,307.8,1565,35.3,119
3850,1,302.3,311.0,1421,41.3,182
4962,1,304.0,312.7,1456,51.2,160
3886,2,302.4,311.3,1392,50.5,51
5437,1,302.9,312.6,1394,46.4,82
...,...,...,...,...,...,...
3919,3,302.5,311.5,1655,32.3,142
162,2,298.3,308.1,1586,35.5,0
7903,2,300.8,312.3,1435,44.8,134
2242,2,299.2,308.4,1667,29.0,199
2745,1,299.7,309.1,1603,38.5,170

In [33]:
pred_test = model.predict(X_test)
pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
(pred_test == y_test).mean()

0.9865